# Generated by Django 5.0.6 on 2024-06-06 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fibra', models.CharField(choices=[('400mb', '400mb'), ('800mb', '800mb'), ('1gb', '1GB')], max_length=10)),
                ('router_bicanal', models.BooleanField(default=False)),
                ('extensor_wifi', models.BooleanField(default=False)),
                ('fecha_instalacion', models.DateField()),
                ('hora_instalacion', models.TimeField()),
                ('comentario_adicional', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.cliente')),
            ],
        ),
    ]
